name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.less'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.less'
      - '.github/workflows/**'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Lint
        run: pnpm lint
